# Use postgres/example user/password credentials
version: "3.1"

services:
  gorawsqldb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: gorawsql
    ports:
      - 5444:5432
  gorawsqldb_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: gorawsql_test
    ports:
      - 5555:5432
